import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Printer, Loader2 } from "lucide-react";
import { inr } from "@/lib/format";

export const Route = createFileRoute("/_authenticated/contracts_/$id/print")({
  head: () => ({ meta: [{ title: "Contract · Print · BrandBridge" }] }),
  component: PrintContract,
});

function PrintContract() {
  const { id } = Route.useParams();
  const { data: c } = useQuery({
    queryKey: ["contract-print", id],
    queryFn: async () => (await supabase.from("contracts")
      .select("*, brand:profiles!brand_id(full_name, brand_name, email), creator:profiles!creator_id(full_name, email)")
      .eq("id", id).maybeSingle()).data,
  });

  if (!c) return <div className="grid min-h-screen place-items-center"><Loader2 className="h-6 w-6 animate-spin" /></div>;

  return (
    <div className="mx-auto max-w-3xl bg-white p-10 text-black">
      <style>{`@media print { .no-print { display: none !important; } body { background: white; } }`}</style>
      <div className="no-print mb-6 flex justify-end">
        <Button onClick={() => window.print()} className="bg-hero-gradient text-white"><Printer className="mr-2 h-4 w-4" />Print / Save PDF</Button>
      </div>
      <h1 className="font-display text-3xl font-bold">Collaboration Agreement</h1>
      <p className="mt-1 text-sm text-gray-600">Contract ID: {c.id}</p>
      <p className="mt-1 text-sm text-gray-600">Created: {new Date(c.created_at).toLocaleDateString()}</p>

      <section className="mt-8 grid grid-cols-2 gap-6">
        <div>
          <h3 className="text-xs uppercase tracking-wider text-gray-500">Brand</h3>
          <p className="mt-1 font-semibold">{c.brand?.brand_name || c.brand?.full_name}</p>
          <p className="text-sm text-gray-600">{c.brand?.email}</p>
        </div>
        <div>
          <h3 className="text-xs uppercase tracking-wider text-gray-500">Creator</h3>
          <p className="mt-1 font-semibold">{c.creator?.full_name}</p>
          <p className="text-sm text-gray-600">{c.creator?.email}</p>
        </div>
      </section>

      <section className="mt-8">
        <h2 className="font-display text-xl font-bold">{c.title}</h2>
        <p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed">{c.terms}</p>
      </section>

      {c.deliverables && (
        <section className="mt-6">
          <h3 className="font-semibold">Deliverables</h3>
          <p className="mt-1 text-sm">{c.deliverables}</p>
        </section>
      )}

      <section className="mt-6 grid grid-cols-2 gap-6 text-sm">
        <div><b>Amount:</b> {inr(c.amount)}</div>
        {c.due_date && <div><b>Due:</b> {c.due_date}</div>}
        <div><b>Status:</b> <span className="capitalize">{c.status.replace("_", " ")}</span></div>
      </section>

      <section className="mt-12 grid grid-cols-2 gap-12">
        <div>
          <p className="border-b border-gray-400 pb-1 font-semibold">{c.brand_signature || "—"}</p>
          <p className="mt-1 text-xs text-gray-600">Brand signature{c.brand_signed_at ? ` · ${new Date(c.brand_signed_at).toLocaleDateString()}` : ""}</p>
        </div>
        <div>
          <p className="border-b border-gray-400 pb-1 font-semibold">{c.creator_signature || "—"}</p>
          <p className="mt-1 text-xs text-gray-600">Creator signature{c.creator_signed_at ? ` · ${new Date(c.creator_signed_at).toLocaleDateString()}` : ""}</p>
        </div>
      </section>

      <p className="mt-10 text-center text-xs text-gray-400">Generated by BrandBridge AI</p>
    </div>
  );
}
